# -*- coding: utf-8 -*-
"""Temptransformersepsis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BzO3N5utWAtncXT1ObWFYU2MVAhslYWp
"""

try:
    from google.colab import drive
    drive.mount('/content/drive')
except ImportError:
    pass   # running locally; data is read from data/ instead

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ==============================================================================
# VISUAL 1: CONFUSION MATRICES (HOSPITAL A vs HOSPITAL B)
# ==============================================================================
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Normalized confusion matrices (percentages)
cm_a = np.array([[0.5565, 0.4435],
                 [0.1949, 0.8051]])

cm_b = np.array([[0.6826, 0.3174],
                 [0.4177, 0.5823]])

labels = ['No Sepsis', 'Sepsis']

# Hospital A Plot
sns.heatmap(cm_a, annot=True, fmt='.1%', cmap='Blues', ax=axes[0],
            xticklabels=labels, yticklabels=labels, cbar=False, annot_kws={"size": 12, "weight": "bold"})
axes[0].set_title('Internal Validation: Hospital A (Threshold = 0.10)', fontsize=12, pad=10)
axes[0].set_xlabel('Predicted Label', fontsize=11)
axes[0].set_ylabel('True Label', fontsize=11)

# Hospital B Plot
sns.heatmap(cm_b, annot=True, fmt='.1%', cmap='Greens', ax=axes[1],
            xticklabels=labels, yticklabels=labels, cbar=False, annot_kws={"size": 12, "weight": "bold"})
axes[1].set_title('External Test: Hospital B (Threshold = 0.11)', fontsize=12, pad=10)
axes[1].set_xlabel('Predicted Label', fontsize=11)
axes[1].set_ylabel('True Label', fontsize=11)

plt.suptitle('Temporal Transformer Confusion Matrices', fontsize=14, y=1.02, weight='bold')
plt.tight_layout()
plt.show()

# ==============================================================================
# VISUAL 2: INTEGRATED GRADIENTS FEATURE IMPORTANCE BAR CHART
# ==============================================================================
features = [
    'Creatinine', 'Glucose', 'MAP', 'Resp', 'HCO3',
    'Hgb', 'Temp', 'BUN', 'Lactate', 'HR_delta3h'
]
scores = [0.35469, 0.25582, 0.21638, 0.21550, 0.18407,
          0.16674, 0.15826, 0.15793, 0.10049, 0.09173]

df_ig = pd.DataFrame({'Feature': features, 'Attribution': scores}).sort_values('Attribution', ascending=True)

plt.figure(figsize=(9, 5))
plt.barh(df_ig['Feature'], df_ig['Attribution'], color='#1f77b4', edgecolor='black', alpha=0.85)
plt.xlabel('Integrated Gradients Attribution Score', fontsize=11, labelpad=8)
plt.title('Top 10 Feature Importances on External Hospital B', fontsize=13, pad=12, weight='bold')
plt.grid(axis='x', linestyle='--', alpha=0.7)

# Annotate exact score values next to bars
for index, value in enumerate(df_ig['Attribution']):
    plt.text(value + 0.005, index, f"{value:.4f}", va='center', fontsize=10)

plt.xlim(0, 0.40)
plt.tight_layout()
plt.show()

# ==============================================================================
# ENHANCED CAUSAL TRANSFORMER (ADVANCED FEATURES & FOCAL LOSS)
# ==============================================================================

import os
import math
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import (
    roc_auc_score, average_precision_score, brier_score_loss,
    confusion_matrix, f1_score
)
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# ------------------------------------------------------------------------------
# 1. SETUP & PATH CONFIGURATION
# ------------------------------------------------------------------------------
try:
    from google.colab import drive
    drive.mount('/content/drive')
except ImportError:
    pass

PATH_A = "data/combinedA_patient_id_cleaned.csv"
PATH_B = "data/combinedB_patient_id_cleaned.csv"

# Global Reproducibility Seeds
SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"[Setup] Executing Advanced Pipeline on: {device}")

# ------------------------------------------------------------------------------
# 2. ENHANCED FEATURE ENGINEERING & PREPROCESSING
# ------------------------------------------------------------------------------
print("\n[1/6] Loading datasets, computing rolling stats, dt features, and dropping shortcuts...")
df_a_raw = pd.read_csv(PATH_A)
df_b_raw = pd.read_csv(PATH_B)

id_col = 'patient_id' if 'patient_id' in df_a_raw.columns else 'Patient_ID'
target_col = 'SepsisLabel' if 'SepsisLabel' in df_a_raw.columns else 'sepsislabel'

# Advanced Feature Engineering: Deltas, Rolling Stats, and Continuous Elapsed Time (dt)
def add_advanced_clinical_features(df, id_c='patient_id'):
    df_proc = df.copy()
    key_vitals = ['HR', 'MAP', 'Resp', 'Temp', 'O2Sat', 'SBP', 'DBP']

    # 1. 3-Hour Rates of Change (Deltas)
    for col in key_vitals:
        if col in df_proc.columns:
            df_proc[f"{col}_delta3h"] = df_proc.groupby(id_c)[col].diff(periods=3).fillna(0.0)

    # 2. 6-Hour Rolling Aggregations (Min, Max, Mean)
    for col in ['HR', 'MAP', 'Resp', 'Temp']:
        if col in df_proc.columns:
            df_proc[f"{col}_min_6h"] = df_proc.groupby(id_c)[col].transform(lambda x: x.rolling(6, min_periods=1).min())
            df_proc[f"{col}_max_6h"] = df_proc.groupby(id_c)[col].transform(lambda x: x.rolling(6, min_periods=1).max())
            df_proc[f"{col}_mean_6h"] = df_proc.groupby(id_c)[col].transform(lambda x: x.rolling(6, min_periods=1).mean())

    # 3. Continuous Elapsed Time Since Last Measurement (delta_t in hours)
    ignore_cols = [id_c, target_col, 'SepsisLabel', 'sepsislabel', 'Unit1', 'Unit2', 'HospAdmTime', 'ICULOS']
    physio_cols = [c for c in df.columns if c not in ignore_cols]
    for col in physio_cols:
        is_nan = df_proc[col].isna()
        # Cumulative count of consecutive NaNs
        df_proc[f"{col}_elapsed_hrs"] = df_proc.groupby(id_c)[col].transform(
            lambda s: s.isna().astype(int).groupby((~s.isna()).cumsum()).cumsum()
        ).fillna(0.0)

    return df_proc

df_a_raw = add_advanced_clinical_features(df_a_raw, id_c=id_col)
df_b_raw = add_advanced_clinical_features(df_b_raw, id_c=id_col)

# Explicitly drop administrative artifacts AND institutional shortcuts (FiO2 and Calcium)
cols_to_drop = [
    id_col, target_col, 'SepsisLabel', 'sepsislabel', 'patient_id', 'Patient_ID',
    'Unit1', 'Unit2', 'HospAdmTime', 'ICULOS', 'FiO2', 'Calcium'  # Removed shortcuts
]

raw_physio_cols = [c for c in df_a_raw.columns if c not in cols_to_drop]

# Forward-fill physiological values and compute medians for unobserved start values
def add_missingness_and_impute(df, physio_cols, id_c, medians=None):
    df_proc = df.copy()

    # Binary missingness masks for base physiological variables
    base_cols = [c for c in physio_cols if not (c.endswith('_delta3h') or c.endswith('_min_6h') or c.endswith('_max_6h') or c.endswith('_mean_6h') or c.endswith('_elapsed_hrs'))]
    for col in base_cols:
        df_proc[f"{col}_is_missing"] = df_proc[col].isna().astype(np.float32)

    # Forward-fill missing observations
    df_proc[physio_cols] = df_proc.groupby(id_c)[physio_cols].ffill()

    # Apply baseline medians
    if medians is None:
        medians = df_proc[physio_cols].median()
    df_proc[physio_cols] = df_proc[physio_cols].fillna(medians)

    missing_cols = [f"{col}_is_missing" for col in base_cols]
    all_feature_cols = physio_cols + missing_cols
    return df_proc, all_feature_cols, medians

df_a_proc, all_feature_cols, hospA_medians = add_missingness_and_impute(df_a_raw, raw_physio_cols, id_col)
df_b_proc, _, _ = add_missingness_and_impute(df_b_raw, raw_physio_cols, id_col, medians=hospA_medians)

# ------------------------------------------------------------------------------
# 3. PATIENT-LEVEL TRAIN / VAL SPLIT (HOSPITAL A)
# ------------------------------------------------------------------------------
print("\n[2/6] Performing patient-level Train/Val split on Hospital A (80/20)...")
patient_ids_a = df_a_proc[id_col].unique()
train_ids, val_ids = train_test_split(patient_ids_a, test_size=0.20, random_state=SEED)

df_train_a = df_a_proc[df_a_proc[id_col].isin(train_ids)].copy()
df_val_a = df_a_proc[df_a_proc[id_col].isin(val_ids)].copy()

# Fit StandardScaler strictly on Hospital A Training Patients
scaler = StandardScaler()
scaler.fit(df_train_a[all_feature_cols])

df_train_a[all_feature_cols] = scaler.transform(df_train_a[all_feature_cols])
df_val_a[all_feature_cols] = scaler.transform(df_val_a[all_feature_cols])
df_b_proc[all_feature_cols] = scaler.transform(df_b_proc[all_feature_cols])

# ------------------------------------------------------------------------------
# 4. 3D TENSOR CREATION
# ------------------------------------------------------------------------------
MAX_SEQ_LEN = 48

def build_3d_tensors(df, feature_cols, max_seq_len=48, id_c='patient_id', target_c='SepsisLabel'):
    grouped = df.groupby(id_c)
    num_patients = len(grouped)
    num_features = len(feature_cols)

    X_arr = np.zeros((num_patients, max_seq_len, num_features), dtype=np.float32)
    y_arr = np.zeros((num_patients, max_seq_len), dtype=np.float32)
    padding_mask = np.ones((num_patients, max_seq_len), dtype=bool)

    for idx, (_, group) in enumerate(grouped):
        seq_len = min(len(group), max_seq_len)
        X_arr[idx, :seq_len, :] = group[feature_cols].values[:seq_len]
        y_arr[idx, :seq_len] = group[target_c].values[:seq_len]
        padding_mask[idx, :seq_len] = False

    return (
        torch.tensor(X_arr, dtype=torch.float32),
        torch.tensor(y_arr, dtype=torch.float32),
        torch.tensor(padding_mask, dtype=torch.bool)
    )

X_train_a, y_train_a, mask_train_a = build_3d_tensors(df_train_a, all_feature_cols, MAX_SEQ_LEN, id_col, target_col)
X_val_a, y_val_a, mask_val_a = build_3d_tensors(df_val_a, all_feature_cols, MAX_SEQ_LEN, id_col, target_col)
X_test_b, y_test_b, mask_test_b = build_3d_tensors(df_b_proc, all_feature_cols, MAX_SEQ_LEN, id_col, target_col)

class SepsisDataset(Dataset):
    def __init__(self, X, y, mask):
        self.X, self.y, self.mask = X, y, mask
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx], self.mask[idx]

train_loader = DataLoader(SepsisDataset(X_train_a, y_train_a, mask_train_a), batch_size=64, shuffle=True)
val_loader = DataLoader(SepsisDataset(X_val_a, y_val_a, mask_val_a), batch_size=64, shuffle=False)
test_b_loader = DataLoader(SepsisDataset(X_test_b, y_test_b, mask_test_b), batch_size=64, shuffle=False)

print(f"  -> Features per timestep (with deltas, rolling stats, dt, & missingness): {len(all_feature_cols)}")
print(f"  -> Train Patients: {len(X_train_a)} | Val Patients: {len(X_val_a)} | External Hosp B Patients: {len(X_test_b)}")

# ------------------------------------------------------------------------------
# 5. CAUSAL TRANSFORMER & FOCAL LOSS ARCHITECTURE
# ------------------------------------------------------------------------------
class FocalLoss(nn.Module):
    def __init__(self, alpha=0.25, gamma=2.0):
        super().__init__()
        self.alpha = alpha
        self.gamma = gamma

    def forward(self, logits, targets):
        bce_loss = nn.functional.binary_cross_entropy_with_logits(logits, targets, reduction='none')
        probs = torch.sigmoid(logits)
        pt = torch.where(targets == 1, probs, 1 - probs)
        focal_weight = (1 - pt) ** self.gamma
        alpha_weight = torch.where(targets == 1, self.alpha, 1 - self.alpha)
        loss = alpha_weight * focal_weight * bce_loss
        return loss.mean()

# Architecture lives in temporal_transformer_model.py so the demo app can rebuild the
# exact same network when it loads the exported state_dict.
from temporal_transformer_model import (
    PositionalEncoding,
    InputProjectionHead,
    CausalTemporalTransformer,
)

model = CausalTemporalTransformer(
    num_features=len(all_feature_cols),
    d_model=128,
    nhead=8,
    num_layers=4,
    dim_feedforward=256,
    dropout=0.3,
    max_len=MAX_SEQ_LEN
).to(device)

# ------------------------------------------------------------------------------
# 6. EVALUATION METRICS FUNCTION
# ------------------------------------------------------------------------------
def evaluate_metrics(model, loader, device):
    model.eval()
    all_probs, all_targets = [], []
    with torch.no_grad():
        for bx, by, bmask in loader:
            bx, by, bmask = bx.to(device), by.to(device), bmask.to(device)
            logits = model(bx, src_key_padding_mask=bmask)
            probs = torch.sigmoid(logits)
            valid_mask = ~bmask

            all_probs.extend(probs[valid_mask].cpu().numpy())
            all_targets.extend(by[valid_mask].cpu().numpy())

    all_probs = np.array(all_probs)
    all_targets = np.array(all_targets)

    auc = roc_auc_score(all_targets, all_probs)
    auprc = average_precision_score(all_targets, all_probs)
    brier = brier_score_loss(all_targets, all_probs)

    best_thresh = 0.5
    best_j = -1
    for thresh in np.linspace(0.1, 0.9, 81):
        preds = (all_probs >= thresh).astype(int)
        tn, fp, fn, tp = confusion_matrix(all_targets, preds, labels=[0, 1]).ravel()
        sens = tp / (tp + fn) if (tp + fn) > 0 else 0
        spec = tn / (tn + fp) if (tn + fp) > 0 else 0
        j_stat = sens + spec - 1
        if j_stat > best_j:
            best_j = j_stat
            best_thresh = thresh

    final_preds = (all_probs >= best_thresh).astype(int)
    tn, fp, fn, tp = confusion_matrix(all_targets, final_preds, labels=[0, 1]).ravel()
    sens = tp / (tp + fn) if (tp + fn) > 0 else 0
    spec = tn / (tn + fp) if (tn + fp) > 0 else 0
    f1 = f1_score(all_targets, final_preds)

    return {
        'AUROC': auc, 'AUPRC': auprc, 'Brier': brier,
        'Sensitivity': sens, 'Specificity': spec, 'F1': f1,
        'Optimal_Threshold': best_thresh
    }

# ------------------------------------------------------------------------------
# 7. TRAINING WITH FOCAL LOSS & EXTENDED PATIENCE EARLY STOPPING
# ------------------------------------------------------------------------------
print("\n[3/6] Training Causal Transformer with Focal Loss (alpha=0.25, gamma=2.0)...")

criterion = FocalLoss(alpha=0.25, gamma=2.0)
optimizer = torch.optim.AdamW(model.parameters(), lr=0.0002, weight_decay=0.01)

EPOCHS = 30
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=1e-6)

best_val_auc = -1.0
best_model_path = "best_causal_transformer.pt"
patience = 7
patience_counter = 0

for epoch in range(1, EPOCHS + 1):
    model.train()
    total_loss = 0.0
    for bx, by, bmask in train_loader:
        bx, by, bmask = bx.to(device), by.to(device), bmask.to(device)
        optimizer.zero_grad()
        logits = model(bx, src_key_padding_mask=bmask)
        valid_mask = ~bmask
        loss = criterion(logits[valid_mask], by[valid_mask])
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        total_loss += loss.item()

    scheduler.step()
    avg_loss = total_loss / len(train_loader)

    val_metrics = evaluate_metrics(model, val_loader, device)
    print(f"Epoch {epoch:02d}/{EPOCHS:02d} | Focal Loss: {avg_loss:.4f} | Val A AUROC: {val_metrics['AUROC']:.4f} | Val A AUPRC: {val_metrics['AUPRC']:.4f}")

    if val_metrics['AUROC'] > best_val_auc:
        best_val_auc = val_metrics['AUROC']
        torch.save(model.state_dict(), best_model_path)
        patience_counter = 0
    else:
        patience_counter += 1
        if patience_counter >= patience:
            print(f"\n[Early Stopping Triggered] No validation improvement for {patience} consecutive epochs.")
            print(f"Restoring best checkpoint with Val AUROC: {best_val_auc:.4f}")
            break

# ------------------------------------------------------------------------------
# 8. FINAL EVALUATION REPORT
# ------------------------------------------------------------------------------
print("\n[4/6] Loading best model checkpoint and executing evaluation...")
model.load_state_dict(torch.load(best_model_path))

val_results = evaluate_metrics(model, val_loader, device)
test_b_results = evaluate_metrics(model, test_b_loader, device)

results_df = pd.DataFrame([val_results, test_b_results], index=['Hospital A (Internal Validation)', 'Hospital B (External Test)'])

print("\n" + "="*80)
print("          RESEARCH PUBLICATION METRICS REPORT (ADVANCED MODEL)          ")
print("="*80)
print(results_df.round(4).to_string())
print("="*80)

# ------------------------------------------------------------------------------
# 8b. EXPORT FOR THE DEMO APP
# ------------------------------------------------------------------------------
# Everything the app needs to rebuild an input row goes in the checkpoint: the exact
# engineered feature order, the StandardScaler statistics, and the Hospital A medians
# used to fill unobserved values. Hardcoding 90+ engineered column names in app.py
# would rot the first time this pipeline changes.
print("\n[Export] Saving model + preprocessing for the demo app...")

from pathlib import Path

MODELS_DIR = Path("models")
MODELS_DIR.mkdir(exist_ok=True)

tt_checkpoint = {
    "state_dict": {k: v.detach().cpu() for k, v in model.state_dict().items()},
    "feature_cols": list(all_feature_cols),
    "num_features": len(all_feature_cols),
    "d_model": 128,
    "nhead": 8,
    "num_layers": 4,
    "dim_feedforward": 256,
    "dropout": 0.3,
    "max_seq_len": MAX_SEQ_LEN,
    "scaler_mean": scaler.mean_.astype(np.float32),
    "scaler_scale": scaler.scale_.astype(np.float32),
    "medians": {k: float(v) for k, v in hospA_medians.items()},
    # Youden-J optimal cutoff from the Hospital A validation split, not a naive 0.5.
    "threshold": float(val_results["Optimal_Threshold"]),
    "metrics": {
        "val_a_auroc": float(val_results["AUROC"]),
        "test_b_auroc": float(test_b_results["AUROC"]),
    },
    "trained_on": "combinedA_patient_id_cleaned (Hospital A, 80% train split)",
}

tt_path = MODELS_DIR / "temporal_transformer_sepsis.pt"
torch.save(tt_checkpoint, tt_path)
print(f"  saved {tt_path} ({tt_path.stat().st_size / 1e6:.1f} MB)")
print(f"  features: {len(all_feature_cols)} | max_seq_len: {MAX_SEQ_LEN} | threshold: {tt_checkpoint['threshold']:.3f}")

# Round-trip through the shared class the app uses, so an architecture change fails
# here rather than as a key mismatch inside Streamlit.
_reloaded = torch.load(tt_path, map_location="cpu", weights_only=False)
_check = CausalTemporalTransformer(
    num_features=_reloaded["num_features"], d_model=128, nhead=8, num_layers=4,
    dim_feedforward=256, dropout=0.3, max_len=_reloaded["max_seq_len"]
)
_check.load_state_dict(_reloaded["state_dict"])
print("  reloaded into temporal_transformer_model.CausalTemporalTransformer OK")

# The app derives engineered columns from a single snapshot; every base column it has
# to supply must exist on the form.
import model_utils

_base_needed = {
    c for c in all_feature_cols
    if not c.endswith(("_delta3h", "_min_6h", "_max_6h", "_mean_6h", "_elapsed_hrs", "_is_missing"))
}
_unknown = sorted(c for c in _base_needed if c not in model_utils.FEATURES_BY_NAME)
print("  base columns missing from the app form:", _unknown or "none")

# ------------------------------------------------------------------------------
# 9. INTEGRATED GRADIENTS FEATURE IMPORTANCE
# ------------------------------------------------------------------------------
print("\n[5/6] Computing Integrated Gradients Feature Importance...")

def compute_integrated_gradients(model, X_tensor, mask_tensor, feature_names, device, steps=20):
    model.eval()
    sample_size = min(300, len(X_tensor))
    inputs = X_tensor[:sample_size].to(device)
    masks = mask_tensor[:sample_size].to(device)
    baseline = torch.zeros_like(inputs).to(device)

    scaled_inputs = [baseline + (float(i) / steps) * (inputs - baseline) for i in range(steps + 1)]
    grads = []

    for scaled_input in scaled_inputs:
        scaled_input.requires_grad = True
        logits = model(scaled_input, src_key_padding_mask=masks)
        valid_mask = ~masks
        valid_logits = logits[valid_mask]
        valid_logits.sum().backward()
        grads.append(scaled_input.grad.cpu().numpy())

    avg_grads = np.mean(grads, axis=0)
    integrated_grad = (inputs.cpu().numpy() - baseline.cpu().numpy()) * avg_grads

    valid_mask_3d = (~masks).cpu().numpy()[:, :, None]
    feature_importance = np.abs(integrated_grad * valid_mask_3d).mean(axis=(0, 1))

    return pd.Series(feature_importance, index=feature_names).sort_values(ascending=False)

ig_importance = compute_integrated_gradients(model, X_test_b, mask_test_b, all_feature_cols, device)

print("\nTop 15 Most Important Features via Integrated Gradients (External Hospital B):")
print(ig_importance.head(15).round(5).to_string())

# Plot Top Features
print("\n[6/6] Generating Feature Importance Plot...")
plt.figure(figsize=(10, 6))
ig_importance.head(12).sort_values().plot(kind='barh', color='navy')
plt.xlabel("Integrated Gradients Attribution Score", fontsize=11)
plt.title("Top Feature Importances (Advanced Causal Transformer)", fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# ==============================================================================
# FULL 4-QUADRANT CROSS-HOSPITAL EVALUATION PIPELINE
# ==============================================================================

import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import roc_auc_score, average_precision_score
from sklearn.preprocessing import StandardScaler

# ------------------------------------------------------------------------------
# 1. PATHS & DEVICE SETUP
# ------------------------------------------------------------------------------
try:
    from google.colab import drive
    drive.mount('/content/drive')
except ImportError:
    pass

PATH_A = "data/combinedA_patient_id_cleaned.csv"
PATH_B = "data/combinedB_patient_id_cleaned.csv"

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"[Setup] Executing 4-Quadrant Pipeline on: {device}")

# ------------------------------------------------------------------------------
# 2. DATA LOADING & PREPROCESSING
# ------------------------------------------------------------------------------
print("\n[1/5] Loading and cleaning datasets...")
df_a = pd.read_csv(PATH_A)
df_b = pd.read_csv(PATH_B)

id_col = 'patient_id' if 'patient_id' in df_a.columns else 'Patient_ID'
target_col = 'SepsisLabel' if 'SepsisLabel' in df_a.columns else 'sepsislabel'

cols_to_drop = [
    id_col, target_col, 'SepsisLabel', 'sepsislabel', 'patient_id', 'Patient_ID',
    'Unit1', 'Unit2', 'HospAdmTime', 'ICULOS'
]

feature_cols = [c for c in df_a.columns if c not in cols_to_drop]

# Fit scalers independently per training source to prevent data leakage
scaler_a = StandardScaler().fit(df_a[feature_cols].fillna(df_a[feature_cols].median()))
scaler_b = StandardScaler().fit(df_b[feature_cols].fillna(df_b[feature_cols].median()))

MAX_SEQ_LEN = 48

def build_sequence_tensors(df, feature_cols, scaler, max_seq_len=48, id_c='patient_id', target_c='SepsisLabel'):
    df_sorted = df.copy()
    df_sorted[feature_cols] = df_sorted.groupby(id_c)[feature_cols].ffill()

    for col in feature_cols:
        med_val = scaler.mean_[feature_cols.index(col)]
        df_sorted[col] = df_sorted[col].fillna(med_val)

    df_sorted[feature_cols] = scaler.transform(df_sorted[feature_cols])

    grouped = df_sorted.groupby(id_c)
    num_patients = len(grouped)
    num_features = len(feature_cols)

    X_arr = np.zeros((num_patients, max_seq_len, num_features), dtype=np.float32)
    y_arr = np.zeros((num_patients, max_seq_len), dtype=np.float32)
    padding_mask = np.ones((num_patients, max_seq_len), dtype=bool)

    for idx, (_, group) in enumerate(grouped):
        seq_len = min(len(group), max_seq_len)
        X_arr[idx, :seq_len, :] = group[feature_cols].values[:seq_len]
        y_arr[idx, :seq_len] = group[target_c].values[:seq_len]
        padding_mask[idx, :seq_len] = False

    return (
        torch.tensor(X_arr, dtype=torch.float32),
        torch.tensor(y_arr, dtype=torch.float32),
        torch.tensor(padding_mask, dtype=torch.bool)
    )

# Prepare Tensors scaled by Scaler A
X_a_scaledA, y_a, mask_a = build_sequence_tensors(df_a, feature_cols, scaler_a, MAX_SEQ_LEN, id_col, target_col)
X_b_scaledA, y_b, mask_b = build_sequence_tensors(df_b, feature_cols, scaler_a, MAX_SEQ_LEN, id_col, target_col)

# Prepare Tensors scaled by Scaler B
X_a_scaledB, _, _ = build_sequence_tensors(df_a, feature_cols, scaler_b, MAX_SEQ_LEN, id_col, target_col)
X_b_scaledB, _, _ = build_sequence_tensors(df_b, feature_cols, scaler_b, MAX_SEQ_LEN, id_col, target_col)

class SepsisDataset(Dataset):
    def __init__(self, X, y, mask):
        self.X, self.y, self.mask = X, y, mask
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx], self.mask[idx]

# ------------------------------------------------------------------------------
# 3. TRANSFORMER ARCHITECTURE DEFINITION
# ------------------------------------------------------------------------------
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=500, dropout=0.1):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-np.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        x = x + self.pe[:, :x.size(1)]
        return self.dropout(x)

class TemporalTransformer(nn.Module):
    def __init__(self, num_features, d_model=64, nhead=4, num_layers=2, dim_feedforward=128, dropout=0.2, max_len=48):
        super().__init__()
        self.input_projection = nn.Linear(num_features, d_model)
        self.pos_encoder = PositionalEncoding(d_model, max_len=max_len, dropout=dropout)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=nhead, dim_feedforward=dim_feedforward, dropout=dropout, batch_first=True
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self.classifier = nn.Sequential(
            nn.Linear(d_model, 32), nn.ReLU(), nn.Dropout(dropout), nn.Linear(32, 1)
        )

    def forward(self, x, src_key_padding_mask=None):
        x = self.input_projection(x)
        x = self.pos_encoder(x)
        x = self.transformer_encoder(x, src_key_padding_mask=src_key_padding_mask)
        return self.classifier(x).squeeze(-1)

def evaluate(model, loader, dev):
    model.eval()
    all_probs, all_targets = [], []
    with torch.no_grad():
        for bx, by, bmask in loader:
            bx, bmask = bx.to(dev), bmask.to(dev)
            logits = model(bx, src_key_padding_mask=bmask)
            probs = torch.sigmoid(logits)
            valid_mask = ~bmask
            all_probs.extend(probs[valid_mask].cpu().numpy())
            all_targets.extend(by[valid_mask].numpy())
    auc = roc_auc_score(all_targets, all_probs)
    auprc = average_precision_score(all_targets, all_probs)
    return auc, auprc

def train_model(train_loader, num_features, pos_weight_val, dev, epochs=10):
    model = TemporalTransformer(num_features=num_features).to(dev)
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight_val.to(dev))
    optimizer = torch.optim.AdamW(model.parameters(), lr=0.001, weight_decay=1e-4)

    model.train()
    for ep in range(1, epochs + 1):
        for bx, by, bmask in train_loader:
            bx, by, bmask = bx.to(dev), by.to(dev), bmask.to(dev)
            optimizer.zero_grad()
            logits = model(bx, src_key_padding_mask=bmask)
            valid_mask = ~bmask
            loss = criterion(logits[valid_mask], by[valid_mask])
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
    return model

# ------------------------------------------------------------------------------
# 4. RUNNING PASS 1: TRAIN ON HOSPITAL A
# ------------------------------------------------------------------------------
print("\n[2/5] Training Model A on Hospital A...")
loader_train_a = DataLoader(SepsisDataset(X_a_scaledA, y_a, mask_a), batch_size=64, shuffle=True)
loader_eval_a_on_a = DataLoader(SepsisDataset(X_a_scaledA, y_a, mask_a), batch_size=64, shuffle=False)
loader_eval_a_on_b = DataLoader(SepsisDataset(X_b_scaledA, y_b, mask_b), batch_size=64, shuffle=False)

valid_y_a = y_a[~mask_a]
weight_a = (valid_y_a == 0).sum() / (valid_y_a == 1).sum()

model_a = train_model(loader_train_a, len(feature_cols), weight_a, device, epochs=10)

auc_A_A, auprc_A_A = evaluate(model_a, loader_eval_a_on_a, device)
auc_A_B, auprc_A_B = evaluate(model_a, loader_eval_a_on_b, device)

# ------------------------------------------------------------------------------
# 5. RUNNING PASS 2: TRAIN ON HOSPITAL B
# ------------------------------------------------------------------------------
print("\n[3/5] Training Model B on Hospital B...")
loader_train_b = DataLoader(SepsisDataset(X_b_scaledB, y_b, mask_b), batch_size=64, shuffle=True)
loader_eval_b_on_b = DataLoader(SepsisDataset(X_b_scaledB, y_b, mask_b), batch_size=64, shuffle=False)
loader_eval_b_on_a = DataLoader(SepsisDataset(X_a_scaledB, y_a, mask_a), batch_size=64, shuffle=False)

valid_y_b = y_b[~mask_b]
weight_b = (valid_y_b == 0).sum() / (valid_y_b == 1).sum()

model_b = train_model(loader_train_b, len(feature_cols), weight_b, device, epochs=10)

auc_B_B, auprc_B_B = evaluate(model_b, loader_eval_b_on_b, device)
auc_B_A, auprc_B_A = evaluate(model_b, loader_eval_b_on_a, device)

# ------------------------------------------------------------------------------
# 6. PRINT 4-QUADRANT MATRIX RESULTS
# ------------------------------------------------------------------------------
print("\n" + "="*65)
print("       4-QUADRANT CROSS-HOSPITAL PERFORMANCE MATRIX       ")
print("="*65)
print(f"  Train Hospital A, Test Hospital A (Internal):  AUROC = {auc_A_A:.4f} | AUPRC = {auprc_A_A:.4f}")
print(f"  Train Hospital A, Test Hospital B (External):  AUROC = {auc_A_B:.4f} | AUPRC = {auprc_A_B:.4f}")
print("-" * 65)
print(f"  Train Hospital B, Test Hospital B (Internal):  AUROC = {auc_B_B:.4f} | AUPRC = {auprc_B_B:.4f}")
print(f"  Train Hospital B, Test Hospital A (External):  AUROC = {auc_B_A:.4f} | AUPRC = {auprc_B_A:.4f}")
print("="*65)
print(f"  Cross-Hospital AUROC Shift (A -> B): {auc_A_B - auc_A_A:+.4f}")
print(f"  Cross-Hospital AUROC Shift (B -> A): {auc_B_A - auc_B_B:+.4f}")
print("="*65)